### ISSUE TITLE
Need Advice

### ISSUE THREAD

**Issue by prepare** [prepare/NRasterizer#1]
@vidstige
I can't modify the existing repo effectively.
so I can't send you a pull request.

what i have done:

1.  cda6899c70a158185595b8590b52317dbe58dc3a
  
   this point, I modify only the font loading part, 
   by add code from my FontRasterizer repo.
   and I move the render model to another  (temp) repo (NRas).
   at this point, no rendering code. 
  

2. I  can't fix the existing rendering elements  (line, segment, bezier etc),  
    so, for reference, I add rendering code by replace some
   existing code with PixelFarm's MiniAgg (the same with my FontRasterizer).
    
   see 0ba8789df9a8f9b9bac3b6c783101f9779a7ac4f
  
  ![](https://raw.githubusercontent.com/prepare/NRasterizer/0ba8789df9a8f9b9bac3b6c783101f9779a7ac4f/screenshots/_2.png)
   
I think you want to preserve the  existing rendering elements.
and I want to ask you about your plan for that.
but its easy to build the glyph model that base on that elements
by create a new GlyphPathBuilderBase object
like I've done in https://github.com/prepare/NRasterizer/blob/v_dev/NRast/GlyphPathBuilderVxs.cs

**Comment by vidstige** [comment]
Yeah, I plan to move out some the rasterizer stuff to it's own project so we can have a clean loading library with the "base class" you've made. But I'm also changing that to a interface probably. I'll ping you here when it's done. Hopefully I can do it tomorrow.

**Comment by vidstige** [comment]
I want to have an interface of the abstract methods in your class, and then a general drawing class that will advance the x-corodinate, etc, basically the long function in your base-class.

**Comment by vidstige** [comment]
I'm committing the class here, but what author should I use? `prepare <???@???.???>`?

**Comment by prepare** [comment]
for me =>  WinterDev

**Comment by vidstige** [comment]
Alright. Paste results of `git config user.name` and `git config user.email`

**Comment by prepare** [comment]
that is 
wintercoredev   at    gmail.com

but I don't check that email frequently,
so user will not get response if he/she send e-mail to me.

**Comment by vidstige** [comment]
no, no. Just so that it will get linked to your github account. :-) I don't want to take credit. But now time to sleep here. I'm in stockholm timezone GMT+1.

**Comment by vidstige** [comment]
I made a few quick commits right now. What do you mean you cannot edit the code effectively? Would it help if I added you as a collaborator? I'd gladly do! :-) But if so, please make pull requests, I want to review all code.

**Comment by prepare** [comment]
> What do you mean you cannot edit the code effectively? 

I mean, After I edited the original code, I can't solve rendering issues with the
existing render elements  as describe above.

But now,  It's solved. (separate rendering part to another project)

> Would it help if I added you as a collaborator?

Haha, 
I think the current status is OK, 
so => not this time now,
but thank you very much.
